name: Render and publish

on:
    workflow_dispatch:
    push:
      # only for .qmd file and .yml files
      paths:
        - '**.qmd'
        - '**.yml'
      branches:
        - master
        - deepak

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish-site:
    runs-on: ubuntu-latest
    container:
      image: sibswiss/training-singlecell-rstudio:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build site
        run: |
          quarto render
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: ./_site